version: "3"
services:
  app:
    image: amara-app
    command: app
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      WORKERS: "2"
      DISABLE_LOGIN_CAPTCHA: "1"
      DISABLE_DEBUG_TOOLBAR: "1"
    volumes:
      - ..:/opt/apps/amara:z
    depends_on:
      - db
      - redis
    ports:
      - "8000"

  worker:
    image: amara-app
    command: worker
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
    volumes:
      - ..:/opt/apps/amara:z
    links:
      - db
      - redis

  feed-worker:
    image: amara-app
    command: feed_worker
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - ..:/opt/apps/amara:z
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: amara
      MYSQL_USER: amara
      MYSQL_PASSWORD: amara
      MYSQL_DATABASE: amara
    volumes:
      - ../docker-dev/mysql/conf.d/:/etc/mysql/conf.d:z
    ports:
      - "3306"

  redis:
    image: redis:4.0.10

  varnish:
    image: amara/amara-cache
    ports:
      - "80"
    networks:
      default:
        aliases:
          - unisubs.example.com
    environment:
      BACKEND_PORT: 8000
      BACKEND_HOST: app
    depends_on:
      - app

  selenium:
    image: selenium/standalone-chrome:3.14.0
    ports:
      - "4444:4444"
    volumes:
      - "/dev/shm:/dev/shm"

  test:
    image: amara-app
    command: ["test", "--gui"]
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      GUITEST_HOSTNAME: unisubs.example.com
      LANG: en_US.UTF-8
    volumes:
      - ..:/opt/apps/amara:z
      - amara-pytest-data:/var/run/pytest/
    depends_on:
      - db
      - selenium
      - varnish
      - worker

volumes:
  amara-pytest-data:
