version: "3"
services:
  app:
    image: amara-app
    command: app
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      WORKERS: 2
      JSON_LOGGING:
      DB_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - asset-builder

  worker:
    image: amara-app
    command: worker
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    depends_on:
      - db
      - redis

  feed-worker:
    image: amara-app
    command: manage feedworker
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    depends_on:
      - db
      - redis

  scheduler:
    image: amara-app
    command: scheduler
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: amara
      MYSQL_USER: amara
      MYSQL_PASSWORD: amara
      MYSQL_DATABASE: amara
    volumes:
      - ./docker-dev/mysql/conf.d/:/etc/mysql/conf.d:z
    ports:
      - "3306"

  redis:
    image: redis:4.0.10

  asset-builder:
    image: node:9.0.0
    environment:
      SKIP_UGLIFY: "1"
    volumes:
      - .:/mnt
    working_dir: /mnt/amara-assets
    command: ['node', 'node_modules/gulp/bin/gulp.js']

  varnish:
    image: amara/amara-cache
    ports:
      - "9000:80"

  test:
    image: amara-app
    command: test
    volumes:
      - .:/opt/apps/amara:z
      - amara-pytest-data:/var/run/pytest/
volumes:
  amara-pytest-data:
